<?php

include_once('piropublic.features.inc');


/**
 * Implement hook_init()
 */
function piropublic_init() {
  if (variable_get('theme_default', 'garland')=='liberty'){
    drupal_add_css(drupal_get_path('module', 'piropublic') .'/css/footer_bottom.css');
  }
}

/**
* Implements hook_uuid_node_features_export_render_alter()
*/
function piropublic_uuid_node_features_export_render_alter(&$export, $node, $module) {
  // don't allow uuid_features to export node properties that can change on deployment
  unset($export->changed);
  unset($export->created);
  unset($export->revision_uuid);
  unset($export->last_comment_timestamp);
  unset($export->revision_timestamp);
  unset($export->data);
  unset($export->picture);
  unset($export->old_status);
  unset($export->date);
  // webform stores nid
  if(isset($export->webform)) {
    unset($export->webform['nid']);
    foreach($export->webform['components'] as $key => $wf) {
      unset($export->webform['components'][$key]['nid']);
    }
  }
}