<?php

include_once('piropublic_about.features.inc');

/**
 * Implementation of hook_init()
 */
function piropublic_about_init() {
  //drupal_add_css(drupal_get_path('module', 'piropublic_about') . '/css/piropublic.css');
  drupal_add_js(drupal_get_path('module', 'piropublic_about') . '/js/piropublic_about.js');
  if (file_exists(drupal_get_path('module', 'piropublic_about') . '/css/' . variable_get('theme_default', 'garland'). '.css')) {
    drupal_add_css(drupal_get_path('module', 'piropublic_about') . '/css/' . variable_get('theme_default', 'garland'). '.css');
  }
}

/**
* Implements hook_theme().
*//*
function piropublic_about_theme() {
  return array(
    // need to use custom template to fix link module target=blank fail
  	'views_view_fields__legislative_efforts' => array(
      'template' => 'views-view-fields--legislative-efforts',
      'original hook' => 'views_view_fields',
      'path' => drupal_get_path('module', 'piropublic') . '/templates/',
   	  'preprocess functions' => array(
      	'template_preprocess',
      	'template_preprocess_views_view_fields',
        'piropublic_preprocess_views_view_fields__legislative_efforts',
      ),
      'arguments' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
    ),
  );
}*/

/**
* Implements hook_uuid_node_features_export_render_alter()
*/
function piropublic_about_uuid_node_features_export_render_alter(&$export, $node, $module) {
  // don't allow uuid_features to export node properties that can change on deployment
  unset($export->changed);
  unset($export->created);
  unset($export->revision_uuid);
  unset($export->last_comment_timestamp);
  unset($export->revision_timestamp);
  unset($export->data);
  unset($export->picture);
  unset($export->old_status);
  unset($export->date);
  // webform stores nid
  if(isset($export->webform)) {
    unset($export->webform['nid']);
    foreach($export->webform['components'] as $key => $wf) {
      unset($export->webform['components'][$key]['nid']);
    }
  }
}